name: FlashMQ

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release
        required: true
        type: string

jobs:
  publish_image:
    name: GitHub Container Registry
    runs-on: ubuntu-latest

    concurrency: flashmq

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: halfgaar/FlashMQ
        ref: ${{ inputs.version }}
        fetch-depth: 0

    - name: Get Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/truebrain/containers/flashmq
        tags: |
          type=semver,pattern={{version}},value=${{ inputs.version }}
          type=semver,pattern={{major}}.{{minor}},value=${{ inputs.version }}
          type=semver,pattern={{major}},value=${{ inputs.version }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout patches
      uses: actions/checkout@v3
      with:
        path: patches

    - name: Apply patches
      run: |
        patch -p1 < patches/flashmq/sse4.patch

    - name: Build & Publish
      id: publish
      uses: docker/build-push-action@v3
      with:
        context: .
        file: patches/flashmq/Dockerfile.buildx
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
